### ISSUE TITLE
false positives

### ISSUE THREAD

**Issue by ruppde** [mthcht/ThreatHunting-Keywords#23]
hi,

these 3 filenames create false positives on windows:

C:\Windows\WinSxS\amd64_windows-senseclient-service_31bf3856ad364e35_10.0.22621.963_none_0a2748035863b8dc\r\SenseCncProxy.exe
C:\Windows\WinSxS\amd64_microsoft-windows-waasmedic_31bf3856ad364e35_10.0.22621.1_none_94e9973331d890c7\WaaSMedicCapsule.dll
C:\Windows\WinSxS\amd64_microsoft-windows-waasmedic_31bf3856ad364e35_10.0.22621.1_none_94e9973331d890c7\WaaSMedicPS.dll

thx
arnim

**Comment by mthcht** [comment]
Hi @ruppde, thanks for the feedback, I really appreciate it! I've removed the irrelevant keywords https://github.com/mthcht/ThreatHunting-Keywords/commit/7b192de3611ace2b2843a3261ec5ef3bb1c97f9a

**Comment by ruppde** [comment]
cool, thx
