### ISSUE TITLE
Add Supernova

### ISSUE THREAD

**Issue by rundll23** [mthcht/ThreatHunting-Keywords#7]
### Link to Official Website/Source Code (if available):
>  [`Supernova`](https://github.com/nickvourd/Supernova)

Can you check this out and add it to the list ?

**Comment by mthcht** [comment]
@rundll23 It's already in the list (merged 3 days ago): https://github.com/mthcht/ThreatHunting-Keywords-sigma-rules/blob/main/sigma_rules/offensive_tools/Supernova/Supernova.json
